name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    name: build
    runs-on: ubunty-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: Build
        run: ./scripts/build.sh
