name: Lint
on:
  push:
    branches:
      - main
  jobs:
    golangci:
      name: lint
      runs-on: ubuntu-latest
      steps:
        - uses: actions/setup-go@v3
          with:
            go-version-file: 'go.mod'
        - uses: actions/checkout@v3
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v3
          with:
            version: latest
            